namespace typeNS
{
    public enum inputType{GAME_START,GIVE_DICE_NUM,GIVE_CHOICE,GIVE_CARD_NUM};
    public enum gameStatus{GAME_CONTINUE};
    public enum BLOCK_TYPE{NONE,ORDINARY,RESTAURANT,HOTEL};
    public enum changeType{NO_CHANGE,PLAYER_ONE_GET,PLAYER_TWO_GET,PLAYER_THREE_GET,PLAYER_FOUR_GET,LEVEL_UP,LEVEL_DOWN,FAILURE};
    public enum charType{CHAR1,CHAR2,CHAR3,CHAR4};
}