namespace typeNS
{
    public enum inputType{GAME_START,GIVE_DICE_NUM,GIVE_CHOICE,GIVE_CARD_NUM};
    public enum gameStatus{GAME_CONTINUE,PLAYER1_OUT,PLAYER2_OUT,PLAYER3_OUT,PLAYER4_OUT,PLAYER1_WIN,PLAYER2_WIN,PLAYER3_WIN,PLAYER4_WIN};
    public enum BLOCK_TYPE{NONE,P0,P1L1,P1L2,P1L3,P2L1,P2L2,P2L3,P3L1,P3L2,P3L3,P4L1,P4L2,P4L3,TREE1,TREE2,TREE3,GUIDE,SNOW,BALL,BIKE,FLOWERS};
    public enum changeType{NO_CHANGE,PLAYER_ONE_GET,PLAYER_TWO_GET,PLAYER_THREE_GET,PLAYER_FOUR_GET,LEVEL_UP,LEVEL_DOWN,FAILURE};
    public enum charType{CHAR1,CHAR2,CHAR3,CHAR4};
}